# -*- coding: utf-8 -*-
"""thinggointernship.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJRG_3YpE8ceZ4bgCYOovpaqN4m-N6Bu
"""

pip install gtts

from gtts import gTTS 
  
# import Os module to start the audio file
import os 
  
mytext = 'Name'
  
# Language we want to use 
language = 'en'
  

myobj = gTTS(text=mytext, lang=language, slow=False) 
  

myobj.save("output.mp3") 
  
# Play the converted file 
os.system("start output.mp3")

import speech_recognition as sr

r = sr.Recognizer()
with sr.Microphone() as source:
    print("Speak Anything :")